---
 - hosts: all
   sudo:  true
   vars:
     pg_username: 'graphite'
     pg_password: 'password'
     pg_create_db: "CREATE USER {{ pg_username }} WITH PASSWORD '{{ pg_password }}';"
   roles:
     - common
     - docker
     #iptables
     - git
     - apache
     - postgres
     - graphite
     - graphite-postgres
