---

  - name: update apt cache
    apt: update_cache=yes cache_valid_time=3600

  - name: upgrade the distro
    apt: upgrade=yes

  - name: install packages
    apt: pkg={{ item }} state=latest
    with_items:
      - build-essential
      - software-properties-common
      - zsh
      - tree
      - vim
      - tmux
      - wget
      - curl
      - ntp
      - ruby
      - python-pycurl
